### PR TITLE
Aaron's initial sprite work

### PR DESCRIPTION
**Pull request by Avienneau**
Here's the initial sprite work.

### CODE REVIEW

**Comment by Brozerker** [comment]
Hey Aaron,Thanks for getting this to me. In the future, though, you can just commit your own changes. And, as I've mentioned before, we are not rendering anything, so I'm not sure if all the code you wrote in sprite is necessary. I believe we're just going to be supplying the graphics core with a list of things for them to render. I'm going to talk with Sam at some point and hopefully get a more concrete plan.
ThanksChris

```
 On Wednesday, September 16, 2015 3:28 PM, Aaron Vienneau <notifications@github.com> wrote:
```

 Here's the initial sprite work. 
You can view, comment on, or merge this pull request online at:
  https://github.com/Brozerker/UICore/pull/1
Commit Summary
- Aaron's initial sprite work

File Changes
-  M GameObject.h (6) 
-  A Sprite.cpp (100) 
-  M Sprite.h (30) 
-  M UICore.vcxproj (16) 
-  M UICore.vcxproj.filters (3) 

Patch Links:
- https://github.com/Brozerker/UICore/pull/1.patch
- https://github.com/Brozerker/UICore/pull/1.diff

**Comment by WBowden** [comment]
Hey nice job guys, sorry i've been not responding this week. I've been
caught up with work and babysitting, but I'm going to hopefully get my part
done by tomorrow. I've noticed Sam doesn't want us rendering, but I can't
find the code he posted in the discussions area from the other email. Since
Sam doesn't want us doing graphics do I still finish off my part with the
graphics or create something else?

**Comment by Brozerker** [comment]
Just got off the phone with Sam. Here's the deal:He's going to write an interface that we're going to use to load our sprites (and positions of the sprites) in to a vector/list, which he should have finished in the next few days. Unfortunately this means that we can't do anything concrete before then, but until that point, we can use Aaron's sprite code for testing.  
 The sprites will consist of 2 buttons, a background image, and the in game health system. It sounds like everyone else is envisioning a point based health system, which means we probably want to do a health bar. We don't have to write any directX code ourselves.I've added some stuff to the google drive such as diagrams that we can use (working on some buttons too). I also shared the folder with you, but in case you don't see it, here's the link:

GSP 420

|   |
|   |  |   |   |   |   |   |
| GSP 420Space Game-User Interface-UML Diagram_UI Core.vsd Sep 11  |
|  |
| View on drive.google.com | Preview by Yahoo |
|  |
|   |

 Aaron, do you want to take care of the list of sprites (just use a placeholder file for now)?Bill, I seem to recall you doing a health bar before? Is that correct?
Thanks guysChris

```
 On Thursday, September 17, 2015 2:49 PM, WillBowden <notifications@github.com> wrote:
```

 Hey nice job guys, sorry i've been not responding this week. I've been
caught up with work and babysitting, but I'm going to hopefully get my part
done by tomorrow. I've noticed Sam doesn't want us rendering, but I can't
find the code he posted in the discussions area from the other email. Since
Sam doesn't want us doing graphics do I still finish off my part with the
graphics or create something else?

**Comment by WBowden** [comment]
Alright Chris,
I'm down to just do some rough testing we can come up with until we can
have something from Sam we can actually get our UI core going.

**Pull request merged**
